apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev
resources:
  - ../../../../../apps/ws-manager/base
  - Ingress.yaml
images:
  - name: intrachat/ws-manager
    newName: ghcr.io/micheleloka/intrachat-ws-manager
    newTag: latest
