apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev
resources:
  - ../../../../../apps/auth-service/base
  - namespace.yaml
  - Ingress.yaml
patchesStrategicMerge:
  - deployment-patch.yaml
images:
  - name: intrachat/auth-service
    newName: ghcr.io/micheleloka/intrachat-auth-service
    newTag: sha-46682ac
