apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev
resources:
  - ../../../../../apps/auth-service/base
  - namespace.yaml
  - Ingress.yaml
patchesStrategicMerge:
  - deployment-patch.yaml
images:
  - name: intrachat/auth-service
    newName: ghcr.io/micheleloka/intrachat-auth-service
    newTag: latest
    digest: sha256:31b4bd6f15929157fb20865c7822d7d03b60be10e0efe959d42d03351f796016
