apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev
resources:
  - ./auth-service/overlay
  - ./chat-service/overlay
  - ./media-service/overlay
  - ./notification-service/overlay
  - ./user-service/overlay
  - ./web-frontend/overlay
  - ./ws-manager/overlay

