apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev
resources:
  - ./auth-service/base
  - ./chat-service/base
  - ./media-service/base
  - ./notification-service/base
  - ./user-service/base
  - ./web-frontend/base
  - ./ws-manager/base
