apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
  - install.yaml
  - image-updater-web-frontend.yaml
  - image-updater-auth-service.yaml
  - image-updater-chat-service.yaml
  - image-updater-media-service.yaml
  - image-updater-notification-service.yaml
  - image-updater-user-service.yaml
  - image-updater-ws-manager.yaml
