apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev
resources:
  - ../../../../../apps/user-service/base
  - Ingress.yaml
images:
  - name: intrachat/user-service
    newName: ghcr.io/micheleloka/intrachat-user-service
    newTag: latest
