apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev
resources:
  - ../../../../../apps/chat-service/base
  - Ingress.yaml
images:
  - name: intrachat/chat-service
    newName: ghcr.io/micheleloka/intrachat-chat-service
    newTag: latest
