apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev
resources:
  - ../../../../../apps/web-frontend/base
  - Ingress.yaml
patchesStrategicMerge:
  - deployment-patch.yaml
images:
  - name: intrachat/web-frontend
    newName: ghcr.io/micheleloka/intrachat-web-frontend
    newTag: latest
    digest: sha256:e26ea4ecb599e61616867ffad8f4a63dff658328eff843ca3eeb3c5c4f2e1932
