apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: staging
resources:
  - ../../../../../platform/keycloak/base
  - namespace.yaml
  - Ingress.yaml
  - secret-admin.yaml
  - secret-db.yaml
