apiVersion: v1
kind: Service
metadata:
  name: web-frontend
  labels:
    app.kubernetes.io/name: web-frontend
    app.kubernetes.io/part-of: intrachat
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: web-frontend
  ports:
    - name: http
      port: 80
      targetPort: http
