apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev
resources:
  - ../../../../../apps/media-service/base
  - Ingress.yaml
images:
  - name: intrachat/media-service
    newName: ghcr.io/micheleloka/intrachat-media-service
    newTag: latest
